.TH "itmages-dolphin-extension" "1" "1.10" "Dmitriy A. Perlow aka DAP-DarkneSS" ""
.SH "NAME"
itmages-dolphin-extension is a Qt application for images upload to ITmag.es.
.br
.SH "SYNTAX"
itmages-dolphin-extension <\fIfilename\fR>
.br
		Opens dialog for upload of image <\fIfilename\fR> to ITmag.es.
.br
.SH "DESCRIPTION"
Allows to quickly upload images to free image hosting ITmag.es in "two clicks".
.br
.SH "OPTIONS"
None.
.br
.SH "AUTHORS"
https://itmag.es
.br
