.TH "franz" "1" "3.1.0" "Dmitriy A. Perlow aka DAP-DarkneSS" "openSUSE Build Service home project"
.SH "NAME"
\fBFranz\fR is a free messaging app / former Emperor of Austria and combines chat & messaging services into one application. Franz currently supports Slack, WhatsApp, WeChat, HipChat, Facebook Messenger, Telegram, Google Hangouts, GroupMe, Skype and many more.
.br
.SH "SEE ALSO"
\fIhttp://meetfranz.com\fR
.br
