.TH "andy-super-great-park" "6" "1.0.8" "Dmitriy A. Perlow aka DAP-DarkneSS" ""
.SH "NAME"
Andy's Super Great Park
.br
.SH "SYNTAX"
andy-super-great-park [\fIoption\fR]
.br
.SH "DESCRIPTION"
Are you frustrated by roller coasters? Are you so bored that you prefer to play chess during the ride? Well, don't worry anymore, you're going to smile again.
.br
Join us in \fBAndy's Super Great Park\fR: the roller coasters from hell which we travel at full speed in a barrage of explosions.
.br
.SH "OPTIONS"
-h, --help	Print this help screen and exit.
.br
--log-concise
.br
			Use a logger that does not output messages that have been recently output.
.br
--log-file	The file to use to store log informations.
.br
--log-level	Level of log informations:
.br
				error: error messages,
.br
				warning: warning and error messages,
.br
				verbose: all messages.
.br
--log-uniq	Use a logger that does not output successively the same message.
.br
-v, --version
.br
			Prints the version of the engine and exit.
.br
--active-area
.br
			The margin around the camera in which we check for activity.
.br
--auto-load-symbols
.br
			Search the items in the game launcher.
.br
--data-path	Path to the directory containing the data of the game.
.br
--dumb-rendering
.br
			Tells to use the dumbest rendering procedure.
.br
--fps		Sets the limit of the number of frames per second.
.br
--fullscreen
.br
			Runs the game in fullscreen mode.
.br
--game-name	The name of the game.
.br
--game-var-assignment
.br
			Changes the delimiter used in --set-game-var-<type> to separate the name and the value of the variable.
.br
--item-library
.br
			Path to a library containing items for the game.
.br
--network-horizon
.br
			The delay to apply to the network messages in term of game iterations. Default is 1.
.br
--no-dumb-rendering
.br
			Tells not to use the dumbest rendering procedure.
.br
--screen-height
.br
			The height of the screen.
.br
--screen-width
.br
			The width of the screen.
.br
--set-game-var-bool
.br
			Sets the value of a boolean game variable.
.br
--set-game-var-int
.br
			Sets the value of an integer game variable.
.br
--set-game-var-real
.br
			Sets the value of a real number game variable.
.br
--set-game-var-string
.br
			Sets the value of a string game variable.
.br
--set-game-var-uint
.br
			Sets the value of a non negative integer game variable.
.br
--start-level
.br
			The path of the first level to run.
.br
--stats-destination
.br
			Sets the value of the destination to which game statistics are sent.
.br
--sync-render
.br
			Tells to do a rendering of the scene for each progress of the game.
.br
--tag		Associates an identifier with this game.
.br
--windowed	Run the game in a window.
.br
.SH "AUTHORS"
\fBStuffomatic\fR is a French company composed of talented friends from Nantes, France. We joined together to develop entertaining games and to share our knowledge in the Operations Research field.
.br
http://www.stuff-o-matic.com
.br
.SH "SEE ALSO"
bf-level-editor(1) bf-model-editor(1) bf-animation-editor(1) bend-image(1)
.br
http://www.stuff-o-matic.com/asgp
.br
