.TH "bend-image" "6" "1.0.8" "Dmitriy A. Perlow aka DAP-DarkneSS" ""
.SH "NAME"
Bear engine
.br
.SH "SYNTAX"
bend-image width height source_image [input_file]
.br
.SH "DESCRIPTION"
This is the \fBBear engine\fR, a set of C++ libraries and tools dedicated to creating great 2D games. It has been used to create Plee the Bear, Andy's Super Great Park and Tunnel.
.br
.SH "OPTIONS"
Points are described in the following format:
.br
p.x p.y [in.x in.y out.x out.y]
.br
If input_file is not set, the points are read from stdin.
.br
.SH "AUTHORS"
\fBStuffomatic\fR is a French company composed of talented friends from Nantes, France. We joined together to develop entertaining games and to share our knowledge in the Operations Research field.
.br
http://www.stuff-o-matic.com
.br
.SH "SEE ALSO"
andy-super-great-park(6) bf-model-editor(6) bf-animation-editor(6) bf-level-editor(6)
.br
https://github.com/j-jorge/bear
.br
