.TH gweled 6  "12/30/2010" "0.7" "gweled Man Page"
.SH NAME
.B gweled 
- a swapping gem game

.SH SYNOPSIS
.B gweled [OPTIONS]

.SH OPTIONS
A summary of the options supported by gweled is included below.
.TP
.B \-\-load\-modules=MODULE1,MODULE2,...
Dynamic modules to load
.SS Help Options
.TP
.B \-?, \-\-help 
Show a help message
.SS GTK+
.TP
.B \-\-gdk\-debug=FLAGS 
Gdk debugging flags to set
.TP
.B \-\-gdk\-no\-debug=FLAGS
Gdk debugging flags to unset
.TP
.B \-\-display=DISPLAY    
X display to use
.TP
.B \-\-screen=SCREEN 
X screen to use
.TP
.B \-\-sync 
Make X calls synchronous
.TP
.B \-\-name=NAME 
Program name as used by the window manager
.TP
.B \-\-class=CLASS  
Program class as used by the window manager
.TP
.B \-\-gtk\-debug=FLAGS 
Gtk+ debugging flags to set
.TP
.B \-\-gtk\-no\-debug=FLAGS 
Gtk+ debugging flags to unset
.TP
.B \-\-g\-fatal\-warnings  
Make all warnings fatal
.TP
.B \-\-gtk\-module=MODULE 
Load an additional Gtk module
.SS Bonobo activation Support
.TP
.B \-\-oaf\-ior\-fd=FD  
File descriptor to print IOR on
.TP
.B \-oaf\-activate\-iid=IID 
IID to activate
.TP
.B \-\-oaf\-private  
Prevent registering of server with OAF
Gnome Library
.TP
.B \-\-disable\-sound
Disable sound server usage
.TP
.B \-\-enable\-sound 
Enable sound server usage
.TP
.B \-\-espeaker=HOSTNAME:PORT
Host:port on which the sound server to use is running
.SS Session management
.TP
.B \-\-sm\-client\-id=ID  
.TP
Specify session management ID
.TP
.B \-\-sm\-config\-prefix=PREFIX 
Specify prefix of saved configuration
.TP
.B \-\-sm\-disable
Disable connection to session manager
.SS GNOME GUI Library
.TP
.B \-\-disable\-crash\-dialog 
Disable crash dialogs

.SH DESCRIPTION
.B gweled 
is a Gnome version of a popular PalmOS/Windows/Java game called
"Bejeweled" or "Diamond Mine". The aim of the game is to make alignment of 3 or
more gems, both vertically or horizontally by swapping adjacent gems. The game
ends when there are no possible moves left.

.SH AUTHORS
The game is developed by Seb Delestaing <sebdelestaing@free.fr> and
Daniele Napolitano <dnax88@gmail.com>.
.br
This little Man Page has been made by Braulio Valdivielso
<brlvldvlsmrtnz@gmail.com>.
.SH SEE ALSO
The project's website: http://www.gweled.org
