.TH "gweled" "6" "12/30/2010" "0.7" "gweled Man Page"
.SH "NAME"
\fBgweled \fR- a swapping gem game
.br

.SH "DESCRIPTION"
\fBgweled \fRis a Gnome version of a popular PalmOS/Windows/Java game called "Bejeweled" or "Diamond Mine". The aim of the game is to make alignment of 3 or more gems, both vertically or horizontally by swapping adjacent gems. The game ends when there are no possible moves left.
.br

.SH "AUTHORS"
The game is developed by Seb Delestaing <sebdelestaing@free.fr> and Daniele Napolitano <dnax88@gmail.com>.
.br
This little Man Page has been made by Braulio Valdivielso <brlvldvlsmrtnz@gmail.com>.
.br

.SH "SEE ALSO"
The project's website: http://www.gweled.org
.br
