.TH "nfsperf" "1" "1.3.7" "Dmitriy A. Perlow aka DAP-DarkneSS" ""
.SH "NAME"
A part of TORCS: The Open Racing Car Simulator.
.br
.SH "DESCRIPTION"
Car Specifications Converter.
.br
.SH "SYNTAX"
nfsperf [-c category.xml] [-i <input carp.txt>] [-o output carp.xml]
.br
.SH "OPTIONS"
-c	category.xml		:	car category description
.br
-i	input carp.txt		:	input NFS carp.txt
.br
-o	output carp.xml	:	converted parameters
.br
.SH "AUTHORS"
http://torcs.sourceforge.net
.br
.SH "SEE ALSO"
texmapper(1) nfs2ac(1) accc(1) torcs(1) trackgen(1)
.br
