.TH "texmapper" "1" "1.3.7" "Dmitriy A. Perlow aka DAP-DarkneSS" ""
.SH "NAME"
A part of TORCS: The Open Racing Car Simulator.
.br
.SH "DESCRIPTION"
Texture Auto Mapper.
.br
.SH "SYNTAX"
texmapper [options]
.br
.SH "OPTIONS"
-f <input acfile>	:	input model file in AC3D format [car.ac]
.br
-o <output acfile>	:	ouput model file in AC3D format [car-out.ac]
.br
-p <parameters>	:	parameters in XML format [texmapper.xml]
.br
-s <file>			:	output skin file [skin.rgb]
.br
--help			:	print this message
.br
.SH "AUTHORS"
http://torcs.sourceforge.net
.br
.SH "SEE ALSO"
nfs2ac(1) accc(1) torcs(1) nfsperf(1) trackgen(1)
.br
