#!/bin/sh
set -e
# Automatically added by dh_makeshlibs
if [ "$1" = "configure" ]; then
    ldconfig 
    gtk-update-icon-cache --force --ignore-theme-index "/usr/share/icons/hicolor"
    glib-compile-schemas "/usr/share/glib-2.0/schemas"
fi
# End automatically added section
