.TH "monster-rpg-2" "6" "2.11.8+20160706" "Dmitriy A. Perlow aka DAP-DarkneSS" ""
.SH "NAME"
An Old School Japanese Style RPG.
.br
.SH "SYNTAX"
monster-rpg-2
.br
.SH "DESCRIPTION"
Monster RPG 2 is a fantasy quest that spans continents and worlds and lets you take a simple villager and develop her into a hero with the power to save her world. The next instalment in the classic Monster RPG series, Monster RPG 2 is a turn-based role-playing game with enough variety, plot twists, secrets, and scenery to keep even the old school players coming back for more. If you loved the 16 bit classics on old console systems, you'll love this game. If you've never heard of those games, you're in for a real treat!
.br
.SH "SEE ALSO"
\fIhttp://nooskewl.ca/monster-rpg-2\fR
.br
