.TH "ap-hotspot" "1" "0.3.1" "Dmitriy A. Perlow aka DAP-DarkneSS" ""
.SH "NAME"
ap-hotspot — Access Point Mode Hotspot.
.br
.SH "SYNTAX"
ap-hotspot
.br
sudo ap-hotspot [\fIoption\fR]
.br
.SH "DESCRIPTION"
A script to create an infrastructure WiFi hotspot (access point mode).
.br
.SH "OPTIONS"
\fBstart\fR	Starts wireless hotspot.
.br
\fBstop\fR	Stop swireless hotspot.
.br
\fBrestart\fR
.br
		Restarts wireless hotspot.
.br
\fBconfigure\fR
.br
		Configures hotspot.
.br
\fBdebug\fR	Starts with detailed messages.
.br
.SH "AUTHORS"
Copyright (C) 2013  Alin Andrei <andrew@webupd8.org>
.br
Copyright (C) 2013  Satyajit sahoo
.br
.SH "SEE ALSO"
http://www.webupd8.org/2013/06/how-to-set-up-wireless-hotspot-access.html
.br
