.TH "qtcmd2" "1" "0.3.1" "Dmitriy A. Perlow aka DAP-DarkneSS" ""
.SH "NAME"
QtCommander is advanced two-panels file manager for Linux Operating System, similar to application for Microsoft Windows named Total Commander or Krusader for KDE.
.br

http://www.qtcmd.org
.br
.SH "SYNTAX"
qtcmd2
.br
.SH "OPTIONS"
none
.br
.SH "AUTHORS"
Piotr Mierzwiński <piom|at|qtcmd.org>
.br
 (the leader of project, main programmer, webmaster, docs writer) 
.br

Mariusz Borowski <b0mar|at|qtcmd.org>
.br
 (programmer, tester, hosting, webdeveloper - web engine, new layout)
.br
