.TH "maxr" "6" "0.2.9" "Dmitriy A. Perlow aka DAP-DarkneSS" "openSUSE games"
.SH "NAME"
M.A.X.R. (Mechanized Assault and eXploration Reloaded)
.br
.SH "SYNTAX"
maxr
.br
.SH "DESCRIPTION"
M.A.X.R. is a fanmade strategy game by the community of maxr.org. MAXR is OpenSource and a remake of the old M.A.X.by Interplay from 1996 featuring network games based on TCP/IP (e.g. over the internet).
.br

.br
The game can be played in a turn-based mode (with or without time limit), or simultaneous mode (all the players take their turns at the same time), and features combat in air, land, and sea. Three resources are present on the maps - Raw Materials, which are needed to manufacture units, structures and ammunition, Fuel, which power generators need to function, and Gold, which is used to purchase upgrades. This game is a mix of realtime and turnbased strategy with battle chess character.
.br
.SH "AUTHORS"
/usr/share/doc/packages/maxr/AUTHORS
.br
.SH "SEE ALSO"
\fIhttp://www.maxr.org\fR
.br
